# Generated by Django 2.2.5 on 2019-09-13 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20190913_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='hotel.Customer'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='hotel.Payments'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='hotel.Bookings'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='hotel.ServiceStaff'),
        ),
    ]
